name: CD / Deploy / Release
concurrency: cd-build

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  get-microservices:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.microservices-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: create-microservices-matrix
        id: microservices-matrix
        run: |
          matrix=$(git diff --name-only ${{github.event.before}} ${{github.event.after}} | grep "^ms-" | sed "s/\(^ms-[^\/]*\).*/\1/" | uniq | xargs -n 1 | jq -R . | jq -sc .)
          echo $matrix
          echo "::set-output name=matrix::$matrix"

  check-matrix:
    runs-on: ubuntu-latest
    needs: get-microservices
    steps:
      - name: Check matrix definition
        run: |
          matrix='${{ needs.microservices-matrix.outputs.matrix }}'
          echo $matrix
          echo $matrix | jq .
          
          
#   build-microservices:
#     runs-on: ubuntu-latest
#     needs: get-microservices
#     strategy:
#       fail-fast: false
#       matrix: 
#         microservices: ${{needs.microservices-matrix.outputs.matrix}} #["ms-authentication"]
    
    
        # -I % sh -c 'docker build -t % --platform linux/x86_64 --build-arg MS_NAME=% -f Dockerfile .'
