name: CD / Deploy / Release
concurrency: cd-build

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  get-microservices:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: git diff --name-only ${{github.event.before}} ${{github.event.before}} | grep "^ms-" | sed "s/\(^ms-[^\/]*\).*/\1/" | uniq
