name: CD / Deploy / Release
concurrency: cd-build

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  get-microservices:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - run: git diff --name-only ${{github.event.before}} ${{github.event.after}} | grep "^ms-" | sed "s/\(^ms-[^\/]*\).*/\1/" | uniq | xargs -I % sh -c 'docker build -t % --platform linux/x86_64 --build-arg MS_NAME=% -f Dockerfile .'
