name: CD / Deploy / Release
concurrency: cd-build

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  get-microservices:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.microservices-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - id: microservices-matrix
        run: |
          matrix=$(git diff --name-only ${{github.event.before}} ${{github.event.after}} | grep "^ms-" | sed "s/\(^ms-[^\/]*\).*/\1/" | uniq | xargs -n 1 | jq -R . | jq -sc .)
          echo $matrix
          echo "::set-output name=matrix::$matrix"
          
          
  build-microservices:
    runs-on: ubuntu-latest
    needs: get-microservices
    strategy:
      fail-fast: false
      matrix: 
        microservices: ${{fromJson(needs.get-microservices.outputs.matrix)}} # np, ca n'est pas une erreur
    steps:
      - name: microservice name
        run: echo ${{matrix.microservices}}
      
      - name: microservice build
        run: docker build -t ${{matrix.microservices}} --build-arg MS_NAME=${{matrix.microservices}} -f Dockerfile .
